-- Enable RLS on all remaining tables
ALTER TABLE IF EXISTS public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.client ENABLE ROW LEVEL SECURITY;  
ALTER TABLE IF EXISTS public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.project_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.project_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.project_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.project_messages ENABLE ROW LEVEL SECURITY;