// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruxfevqchcrdirmhxyfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1eGZldnFjaGNyZGlybWh4eWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTU4NjIsImV4cCI6MjA3MzQzMTg2Mn0.nQN4atbKw4KSpDokV6hOz9kR4vJZovm7GvuQo9bACcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});